version: '3.8'

services:
  # MySQL container (XAMPP-style)
  mysql:
    image: mysql:8.0
    container_name: xenoblade-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d  # DB creation only
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Spring Boot services
  user-auth:
    build: ./user-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    depends_on:
      mysql:
        condition: service_healthy

  xc3:
    build: ./xc3
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/xc3_db?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    depends_on:
      mysql:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    ports:
      - "80:8080"
    depends_on:
      - user-auth
      - xc3

volumes:
  mysql_data:  # Persistent DB storage